### ISSUE TITLE
When starting, takes a long time for initial beat start. Hangs at "Acquiring lock..."

### ISSUE THREAD

**Issue by metachris** [sibson/redbeat#100]
I'm using redbeat with AWS ElastiCache Redis.

When I deploy a new version, the beat service starts, prints the Configuration, shows the stored entries (when running with loglevel DEBUG), and then hangs at `beat: Acquiring lock...` for a loooong time, about 10-30 minutes. Once it proceeds, after that amount of delay  the log says `beat: Extending lock...` and then immediate moves to `Selecting tasks` and proceeding.

I only need redbeat to have multiple celery-beat instances not trigger periodic jobs multiple times.

Wondering why this takes so long (even when there is only one beat instance starting), and what I could try.

Edit: I'm only seeing this issue after redeployments to our AWS infrastructure with ElastriCache, but cannot reproduce it in a local dev environment where Redis is cleared.

**Comment by metachris** [comment]
Thanks for the hint. What do you think of this PR? Not sure how i'd be able to get this into a production setup without having it be part of a PyPI package (would prefer to avoid pulling code from Github and using a development branch to provision the production setup).

But actually, i have the up to 25 minute delay before it says `beat: Extending lock...`, so I'm not sure that this PR could impact that, because it only takes over at that point, at which the delay already happened if i understand correctly.

**Comment by sibson** [comment]
hmm, I think you need is a non-blocking call to aquire, additional logging and retry on failure in https://github.com/sibson/redbeat/blob/master/redbeat/schedulers.py#L419-L426.  The quick answer would be to redis-cli into the server and inspect the lock values to confirm it hasn't been cleaned up.  The other piece to confirm is the cleanup code is being run when you shutdown the old version before deploy, https://github.com/sibson/redbeat/blob/master/redbeat/schedulers.py#L390-L393

**Comment by metachris** [comment]
Yeah I'll check if the lock is set. I'm using Beanstalk with a multi-docker setup, not sure if Beanstalk does a graceful shutdown or just kills the celerybeat docker container. Seems to me it just kills it and the lock would be left over, which would be consistent with the delays of around 25m i've been seeing.

**Comment by metachris** [comment]
Just confirmed that Elastic Beanstalk is not doing a graceful shutdown and the lock is not released when the instance is removed.

**Comment by metachris** [comment]
What do you think could be approaches for redbeat not being shutdown gracefully, and having the lock left over?

**Comment by metachris** [comment]
Would there be any downsides to reducing [`beat_max_loop_interval`](http://docs.celeryproject.org/en/4.0/userguide/configuration.html#std:setting-beat_max_loop_interval) to something like 20 seconds, so the default lock period would be 100 seconds?

**Comment by metachris** [comment]
Update: even if I open a shell into the Docker container and kill the celerybeat process, it does not do a graceful shutdown, still leaves the lock in redis. btw, using latest redbeat 0.11.1

**Comment by sibson** [comment]
I believe upstream celery should be setting up the proper signal handlers and then calling the close() method.  If that is all working properly then I don't think there is much redbeat can do.  Reducing the loop interval would make the CPU and Redis busier, which may or may not be a concern.  You could also adjust the ```redbeat_lock_timeout```.  Changing the lock timeout either way is a workaround rather than a proper solution.

**Comment by mbarszcz** [comment]
I think for critical applications reducing timeout is a must anyway -- because even if celery was cleaning up the lock, the instance may still go down ungracefully and the lock won't be released fast enough.
