### ISSUE TITLE
Beat not picking up configuration on startup

### ISSUE THREAD

**Issue by rajeshyogeshwar** [sibson/redbeat#105]
I am using celery inside a docker container and I am using RedBeatScheduler. The command I use to start celery is

`celery -E -A myapp.taskapp worker --beat --scheduler redbeat.schedulers:RedBeatScheduler --loglevel INFO --uid taskmaster --concurrency=5`

But the problem is that during start beat gets the following error and stops working.

![celeryissye](https://user-images.githubusercontent.com/7311146/50150677-abd25c80-02e4-11e9-8f25-b5ccdfcd56ff.png)

Based on stacktrace, it is clear that `conf` object's `redis_url` property is not set at startup but when I log in check it manually it seems to work and has the said property correctly set. I am unsure if the issue is from `redbeat` or `celery` itself.

**Comment by JohnJiangLA** [comment]
I got the same question. Is there any hints or answers for this issue?

**Comment by JohnJiangLA** [comment]
> I got the same question. Is there any hints or answers for this issue?

I think I got the answer.
I used it in flask, and my code is
```
entry = RedBeatSchedulerEntry('task-name', 'tasks.some_task', interval, args=['arg1', 2])
entry.save()
```
as same as the code in the readme file, and it should pass the celery instance that has set up to the RedBeatSchedulerEntry using app param. so ,it should be:
'''
entry = RedBeatSchedulerEntry('task-name', 'tasks.some_task', interval, args=['arg1', 2], app= 'celery_had_set_up')
'''

**Comment by rajeshyogeshwar** [comment]
@JohnJiangLA I couldn't trace it to anything. But I observed a certain thing, whenever there was a programming error in the tasks to be scheduled this particular error popped up. It can be completely irrelevant, but it is something that I have observed. Once I fixed the programming error, this error is gone. It's misleading.

**Comment by JohnJiangLA** [comment]
> @JohnJiangLA I couldn't trace it to anything. But I observed a certain thing, whenever there was a programming error in the tasks to be scheduled this particular error popped up. It can be completely irrelevant, but it is something that I have observed. Once I fixed the programming error, this error is gone. It's misleading.

@rajeshyogeshwar can you post your code of the `myapp.taskapp` and the process how the scheduled tasks added ? I think my problem is when the entry is built without the celery having the configure object, but a new instance of celery which didn't configured.  

you can see the code in `redbeat/scheduler.py` where the error raising is getting the redis connection. and the `redis_url` is None. So the error raising.

```
entry = RedBeatSchedulerEntry('task-name', 'tasks.some_task', interval, args=['arg1', 2], app= 'celery_had_set_up')
```

this app param passing the celery instance with the configure to the new RedBeatSchedulerEntry object. and this instance has the property `app’ and `conf`. and my problem ended.

**Comment by rajeshyogeshwar** [comment]
This is the piece I use to schedule a task. Here **app** is the instance of Celery app.

```
interval = crontab(hour=1, minute=30, day_of_week='0,1,2,3,4,5,6')
entry = RedBeatSchedulerEntry('task_name', 'app.tasks.task_name', interval, app=app)
entry.save()
print('Scheduled task_name')
```

Given that I faced this problem quite some time back, I was able to resolve it. But if there is even a typo in any of the tasks module then I still get the same error.

**Comment by JohnJiangLA** [comment]
> This is the piece I use to schedule a task. Here **app** is the instance of Celery app.
> 
> ```
> interval = crontab(hour=1, minute=30, day_of_week='0,1,2,3,4,5,6')
> entry = RedBeatSchedulerEntry('task_name', 'app.tasks.task_name', interval, app=app)
> entry.save()
> print('Scheduled task_name')
> ```
> 
> Given that I faced this problem quite some time back, I was able to resolve it. But if there is even a typo in any of the tasks module then I still get the same error.

Sorry, I don't know what the reason why your problem occur.

**Comment by rajeshyogeshwar** [comment]
No issues, it doesn't occur anymore. If it ever does then upon bit of looking into code I have usually found out some errors. So, I am assuming that it would have been case with me.
