### ISSUE TITLE
Provide a way to reset a task when it failed

### ISSUE THREAD

**Issue by arthurzenika** [sibson/redbeat#106]
For some reason we have tasks in redbeat that are not running. 

While debugging the reason why these tasks are not running, we would like to restart a task without waiting the time between tasks (in some of our use cases its 48 hours). 

Looking at the ZRANGE redbeat::schedule we figured that that list would be consumed in order with the timestamp. 

We tweaked something with ZINCRBY with a negative number which enabled use to force a task to run earlier than it was supposed to. 

Then we wrote a small script to generate some ZADD XX commands. eg `ZADD redbeat::schedule XX 1546968532 name-of-task`. This approach doesn't seem to work. Any idea what we are doing wrong ? Is there a better way of doing this ?

**Comment by sibson** [comment]
I don't fully understand your problem, but you should be able to manipulate using zadd as you are suggesting.  If you simply want to run the task one time off schedule why not use [Celery.delay or async_apply](http://docs.celeryproject.org/en/latest/userguide/calling.html#basics) directly, rather than manipulate RedBeat?

**Comment by sibson** [comment]
fair enough, it seems you are on the right track with using zadd.  I wonder if you are hitting issues related to redis 3.0 compatability, https://github.com/sibson/redbeat/issues/107, as I see you are using the ```XX``` option.

**Comment by arthurlogilab** [comment]
@sibson I'm not sure, but I'll take a look. 

We'll take another look with @philpep

**Comment by sibson** [comment]
If you are still experiencing issues, please reopen the issue and provide additional details to help debug further.
