### ISSUE TITLE
Fix the warnings in python37

### ISSUE THREAD

**Issue by laixintao** [sibson/redbeat#121]
Hi I see many warnings during the tests on python37, I open a PR to fix them later.

**Comment by sibson** [comment]
I believe https://github.com/sibson/redbeat/pull/120 fixed the ones that were due to redbeat,  The remaining warnings are in celery 3, which I'll drop support for soon.

**Comment by laixintao** [comment]
Cool, I checked the latest test log, the warnings were from kombu and celery.
