### ISSUE TITLE
Smaller Readme and real docs

### ISSUE THREAD

**Issue by sibson** [sibson/redbeat#124]
The README is starting to get rather long-winded and should be more focused on "selling" why to use redbeat and then a quick start.

The details of how to use and other details should be in proper docs that can be built and hosted somewhere like readthedocs.

**Comment by laixintao** [comment]
I can help, but the code is really good and I used the source as a reference 👍

**Comment by sibson** [comment]
First pass at splitting docs is done, they could probably use some more refinement but that is a separate issue/task.
