### ISSUE TITLE
redis.exceptions.ReadOnlyError: Command # 1 (HSET redbeat:celery.backend_cleanup definition {"name": "celery.backend_cleanup", "

### ISSUE THREAD

**Issue by oguzhannkayaa** [sibson/redbeat#157]
Hi, when I run celery beat -S redbeat.RedBeatScheduler

Configuration ->
    . broker -> amqp://guest:**@localhost:5672//
    . loader -> celery.loaders.app.AppLoader
    . scheduler -> redbeat.schedulers.RedBeatScheduler
       . redis -> redis://remotemachine:6379/0
       . lock -> `redbeat::lock` 25.00 minutes (1500s)
    . logfile -> [stderr]@%WARNING
    . maxinterval -> 5.00 minutes (300s)

CRITICAL/MainProcess] beat raised exception <class 'redis.exceptions.ReadOnlyError'>: ReadOnlyError('Command # 1 (HSET redbeat:celery.backend_cleanup definition {"name": "c                                    elery.backend_cleanup", "task": "celery.backend_cleanup", "args": null, "kwargs": {}, "options": {"expires": 43200}, "schedule": {"__type__": "crontab", "minute": "0", "hour": "4", "day_of_week": "*                                    ", "day_of_month": "*", "month_of_year": "*"}, "enabled": true}) of pipeline caused error: Command # 1 (HSET redbeat:celery.backend_cleanup definition {"name": "celery.backend_cleanup", "task": "cel                                    ery.backend_cleanup", "args": null, "kwargs": {}, "options": {"expires": 43200}, "schedule": {"__type__": "crontab", "minute": "0", "hour": "4", "day_of_week": "*", "day_of_month": "*", "month_of_ye                                    ar": "*"}, "enabled": true}) of pipeline caused error: You can\'t write against a read only replica.',)
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'scheduler'

I am getting this error.

**Comment by sibson** [comment]
If you are still experiencing issues, please reopen the issue and provide additional details to help debug further.
