### ISSUE TITLE
 Any plan to release a new version?

### ISSUE THREAD

**Issue by yeyuqiu** [sibson/redbeat#158]

**Comment by crutcha** [comment]
➕ been waiting for a tag for a while

**Comment by yogevyuval** [comment]
@sibson Any plans?

**Comment by yogevyuval** [comment]
@sibson Sorry to bother, but it seems like many people are waiting for a new version for the latests commits. Are you planning to release, or should we maybe use Redbeat directly from the master branch?

**Comment by michauds** [comment]
FYI, there seems to be a release for 2.0 available on pypi here: https://pypi.org/project/celery-redbeat/
