### ISSUE TITLE
Problems with celery 5.0.0

### ISSUE THREAD

**Issue by oprog** [sibson/redbeat#184]
Hello,

please have a look at this
https://github.com/celery/celery/issues/6369

It looks like redbeat is not working with celery 5.0.0 
Thanks

**Comment by kleschenko** [comment]
This issue [has been already fixed](https://github.com/sibson/redbeat/pull/178) in master but the new version has not been released to PyPI yet

**Comment by oprog** [comment]
🖖 live long and prosper, man.

**Comment by at-cf** [comment]
@kleschenko will it be released soon so that we can move to celery 5
