### ISSUE TITLE
Possible to schedule cron tasks in different timezones?

### ISSUE THREAD

**Issue by cooperbaird** [sibson/redbeat#192]
I noticed the design.rst file for the latest release says the following:

```
Every task schedule maybe created with a timezone independent of the host timezone.
As a result most datetime objects need to be timezone aware.
```

Is this possible to do with cron task schedules?

**Comment by cooperbaird** [comment]
I have tried setting the timezone field manually in the schedule metadata and have tried setting enable_utc = False in my celery config. Neither of these helped. Am I doing something wrong, or is using different timezones for each task not supported for crontab scheduling? I know @laixintao @sempr @noamkush were predominantly the ones who added this new feature. Do you guys have any insight?

**Comment by noamkush** [comment]
`crontab` support is based on `celery.schedules.crontab` objects which don't support custom timezones.
Adding support for timezone in crontabs would need to start with adding support in celery. It might be easier to try to use rrules (if possible).

**Comment by cooperbaird** [comment]
I see. Yeah I've seen some people able to add per-task timezones with `celery.schedules.crontab` by using the crontab nowfun argument (https://stackoverflow.com/questions/21827290/celery-beat-different-time-zone-per-task). This doesn't seem to work with Redbeat, so I assume there'd need to be changes from the Redbeat side of things. Haven't messed around with rrules yet, but that lane looks promising, so I might try that migration in the near future.

**Comment by noamkush** [comment]
`nowfun` is a method, and redbeat needs everything to be json serializable (see [decoder.py](https://github.com/sibson/redbeat/blob/9401c18c78bd33467e848fad4924a60c4a8188a1/redbeat/decoder.py#L96))

**Comment by cooperbaird** [comment]
Ok I gotcha. Yeah looks like rrules might be the way to go then. I haven't investigated them too much, so hopefully they'll fit my use case well.

**Comment by sibson** [comment]
Handling lambda functions might be tricky but for normal functions it should be possible to store the nowfun() function name on encode and then lookup on decode to pass into the constructors.  This is basically how celery manages task names.

**Comment by cooperbaird** [comment]
I like that idea. Assuming the nowfun function name is stored on encode [here](https://github.com/sibson/redbeat/blob/9401c18c78bd33467e848fad4924a60c4a8188a1/redbeat/decoder.py#L96), it looks like where the crontab is built [here](https://github.com/sibson/redbeat/blob/9401c18c78bd33467e848fad4924a60c4a8188a1/redbeat/decoder.py#L54), on decode, it would pick up the nowfun function name and assign it to nowfun as a string (ex. nowfun='function_name') as the code stands now. I think the trickiest thing would be mapping that function name that was stored in redis as a string to a Callable (defined on the client side). Maybe there's a straightforward way to do that, but I'm not sure off-hand.

**Comment by adarshshetty1** [comment]
@cooperbaird I have used crontab(hour=6, minute=30, nowfun=lambda: datetime.datetime.now(pytz.timezone('Europe/Berlin'))) directly and it worked for me with redbeat 2.0.0. I hope you have set enable_utc = False for both the worker and the source from where you are submitting tasks.

**Comment by cooperbaird** [comment]
@adarshshetty1 Interestingly enough I tried that, and it successfully worked 1 time. Every time after that when I've added a task with this approach, it shows 1 task due in the beat process (at the task's scheduled time), but the task isn't dispatched to the worker.

**Comment by cooperbaird** [comment]
@noamkush I've decided to move to rrules seeing that they already support multiple timezones. In testing, however, I noticed that the definition stores a UTC offset in Redis. Does this mean that that rrules don't support DST abiding timezones?

**Comment by noamkush** [comment]
Yeah, as I implemented in #103, the timezone is saved as a number. That was my use case. You can maybe enhance this and add support for both like what was done for `datetime` objects.

**Comment by cooperbaird** [comment]
Ah got it. If I get some time this month, I'll submit a PR.

**Comment by sibson** [comment]
I believe this should work now in 2.x, thanks to https://github.com/sibson/redbeat/pull/165
