### ISSUE TITLE
Adding tasks dynamically in redbeat

### ISSUE THREAD

**Issue by aixue0909** [sibson/redbeat#200]
The code is as follows:
    def addtask(url):
    interval = celery.schedules.schedule(run_every=30) # 20seconds
    entry = RedBeatSchedulerEntry('taskB','tasks.taskB',interval,args=['url',url])
    entry.save()

Error in execution method：
   'NoneType' object has no attribute 'startswith'

**Comment by torugok** [comment]
I believe you should inform your celery app in args of "RedBeatSchedulerEntry", RedBeatSchedulerEntry(app=celery_app)

**Comment by aixue0909** [comment]
Yes, you are right. It has been solved. thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sibson/redbeat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月28日(星期五) 凌晨1:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sibson/redbeat] Adding tasks dynamically in redbeat (#200)





 
I believe you should inform your celery app in args of "RedBeatSchedulerEntry", RedBeatSchedulerEntry(app=celery_app)
