### ISSUE TITLE
Startup fails if app.conf.CELERYBEAT_SCHEDULE.keys() is empty.

### ISSUE THREAD

**Issue by lambacck** [sibson/redbeat#23]
https://github.com/sibson/redbeat/blob/master/redbeat/schedulers.py#L209

**Comment by sibson** [comment]
This could be stale and appears to be working now.  If you are still having issues could you post a traceback or sample config file.

**Comment by sibson** [comment]
maybe fixed by https://github.com/sibson/redbeat/pull/34?

**Comment by lambacck** [comment]
I can't reproduce now so I guess it's gone.
