### ISSUE TITLE
The scheduler may publish task when acquiring the lock failure

### ISSUE THREAD

**Issue by Junzki** [sibson/redbeat#238]
Same as described in #208 
The redbeat acquires the lock here:
https://github.com/sibson/redbeat/blob/main/redbeat/schedulers.py#L515

from the source code above, the scheduler connects to the `beat_init` signal. It will acquire lock on start.

However, according to celery's implementation:
https://github.com/celery/celery/blob/main/celery/utils/dispatch/signal.py#L275

When acquire lock failed, it raises an exception. The celery signal dispatcher will ignore this exception (just print out to the log/stderr), 
and the scheduler will continue to work.

In the situation which have multiple scheduler working in one cluster, there will be more than one scheduler sending tasks at same time.

**Comment by nicklyra** [comment]
We have seen this behavior as well, when at one point we had a misconfiguration in some parameters that caused Redbeat to always throw an exception during startup; in that case, we ended up with every instance in the cluster thinking it needed to publish tasks.  Non-hilarity ensued.
