### ISSUE TITLE
[Question] Ensuring task is scheduled 

### ISSUE THREAD

**Issue by vitormhenrique** [sibson/redbeat#263]
Good morning everyone! 
Question around RedBeat.
II have been using `django-celery-beat` for the last 4 years in prod, but I can't seem to get it working reliable, it always crashes silently somehow (service active but stops sending the tasks) an I can't build an reliable way to measure this and auto recover.
I wanted to give RedBeat a try, I do manage all my tasks today with the admin page, but It will be easy to make some models and manage tasks being added dynamically to RedBeat that is not a problem (I'll create my own periodic task model, and when save add to the RedBeat schedule using the python API). 

But my question is, if somehow redis crashes, keys get erased / flushed or the system restarts with an old snapshot I can loose configuration of the scheduled tasks right?
So I'll also need to write a small service that is monitoring RedBeat if the tasks are indeed scheduled (aka added to the redis cache) and "re add" it if necessary?

**Comment by sibson** [comment]
Yes, you need a way to rehydrate scheduled tasks, in the event that redis crashes.  Some people are using redis-cluster.  Tasks should also be idempotent.   It might even be reasonable to have an adaptor that hydrates redbeat from django-celery-beat database tables.
