### ISSUE TITLE
redis_url is not recognized

### ISSUE THREAD

**Issue by piotrsynowiec** [sibson/redbeat#268]
Hello, I have setup the app, as in docs, but still, redbeat doesn't work:

beta_app-celery-beat-1  | celery beat v5.3.1 (emerald-rush) is starting.
beta_app-celery-beat-1  | __    -    ... __   -        _
beta_app-celery-beat-1  | LocalTime -> 2023-12-11 21:53:36
beta_app-celery-beat-1  | Configuration ->
beta_app-celery-beat-1  |     . broker -> amqp://guest:**@localhost:5672//
beta_app-celery-beat-1  |     . loader -> celery.loaders.default.Loader
beta_app-celery-beat-1  |     . scheduler -> redbeat.schedulers.RedBeatScheduler
beta_app-celery-beat-1  |        . redis -> None
beta_app-celery-beat-1  |        . lock -> `redbeat::lock` 25.00 minutes (1500s)
beta_app-celery-beat-1  |     . logfile -> [stderr]@%INFO
beta_app-celery-beat-1  |     . maxinterval -> 5.00 minutes (300s)
beta_app-celery-beat-1  | [2023-12-11 21:53:36,513: INFO/MainProcess] beat: Starting...
beta_app-celery-beat-1  | [2023-12-11 21:53:36,515: CRITICAL/MainProcess] beat raised exception <class 'AttributeError'>: AttributeError("'NoneType' object has no attribute 'startswith'")
beta_app-celery-beat-1  | Traceback (most recent call last):
beta_app-celery-beat-1  |   File "/usr/local/lib/python3.11/site-packages/celery/apps/beat.py", line 113, in start_scheduler
beta_app-celery-beat-1  |     service.start()
beta_app-celery-beat-1  |   File "/usr/local/lib/python3.11/site-packages/celery/beat.py", line 631, in start
beta_app-celery-beat-1  |     humanize_seconds(self.scheduler.max_interval))
beta_app-celery-beat-1  |                      ^^^^^^^^^^^^^^
beta_app-celery-beat-1  |   File "/usr/local/lib/python3.11/site-packages/kombu/utils/objects.py", line 32, in __get__
beta_app-celery-beat-1  |     return super().__get__(instance, owner)
beta_app-celery-beat-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
beta_app-celery-beat-1  |   File "/usr/local/lib/python3.11/functools.py", line 1001, in __get__
beta_app-celery-beat-1  |     val = self.func(instance)
beta_app-celery-beat-1  |           ^^^^^^^^^^^^^^^^^^^
beta_app-celery-beat-1  |   File "/usr/local/lib/python3.11/site-packages/celery/beat.py", line 674, in scheduler
beta_app-celery-beat-1  |     return self.get_scheduler()
beta_app-celery-beat-1  |            ^^^^^^^^^^^^^^^^^^^^
beta_app-celery-beat-1  |   File "/usr/local/lib/python3.11/site-packages/celery/beat.py", line 665, in get_scheduler
beta_app-celery-beat-1  |     return symbol_by_name(self.scheduler_cls, aliases=aliases)(
beta_app-celery-beat-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
beta_app-celery-beat-1  |   File "/usr/local/lib/python3.11/site-packages/redbeat/schedulers.py", line 379, in __init__
beta_app-celery-beat-1  |     super(RedBeatScheduler, self).__init__(app, **kwargs)
beta_app-celery-beat-1  |   File "/usr/local/lib/python3.11/site-packages/celery/beat.py", line 264, in __init__
beta_app-celery-beat-1  |     self.setup_schedule()
beta_app-celery-beat-1  |   File "/usr/local/lib/python3.11/site-packages/redbeat/schedulers.py", line 391, in setup_schedule
beta_app-celery-beat-1  |     client = get_redis(self.app)
beta_app-celery-beat-1  |              ^^^^^^^^^^^^^^^^^^^
beta_app-celery-beat-1  |   File "/usr/local/lib/python3.11/site-packages/redbeat/schedulers.py", line 119, in get_redis
beta_app-celery-beat-1  |     if conf.redis_url.startswith('redis-sentinel') and 'sentinels' in redis_options:
beta_app-celery-beat-1  |        ^^^^^^^^^^^^^^^^^^^^^^^^^
beta_app-celery-beat-1  | AttributeError: 'NoneType' object has no attribute 'startswith'

when it comes to normal celery - the redis URL is normally passed.

no matter what I write in this line:

redbeat_redis_url = "redis://redis:6379/"

I still have Redis -> None

**Comment by piotrsynowiec** [comment]
I have found that I needed to modify the command line.

**Comment by MohammedAlmeshal** [comment]
@piotrsynowiec could you please share your findings in more detail, I'm facing the same issue 👀

**Comment by piotrsynowiec** [comment]
I needed to change the command:

celery -A app_name beat -S redbeat.RedBeatScheduler -l info
