### ISSUE TITLE
Conda packages for version higher than 2.0.0

### ISSUE THREAD

**Issue by aparnapr121** [sibson/redbeat#269]
Latest conda version available for celery-redbeat is 2.0.0 Subsequeues PyPI releases have a lot of bug fixes. Could you please release them as conda packages as well. I tried doing a conda skeleton and conda build to package them, but this resulted in a lot of errors.

**Comment by sibson** [comment]
I'm not familiar with conda and am unable to support it.  If someone is providing conda packages they will need to provide the updates.
