### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by iggy** [sibson/redbeat#278]
I'm hitting an issue that I found is fixed in https://github.com/sibson/redbeat/commit/ed3b3231668168dfd8f935f3035820e3b8e38f5d however that isn't in a release yet. Would it be possible to do a new release sometime soon?

I also noticed that the most recent release (2.2.0) doesn't show up in the github releases page and when you go to the tag in github, it shows a big warning that the commit isn't included in any branch in the repo which seems a little scary with all the supply chain things going on recently.

**Comment by aprams** [comment]
Thanks for the hint on the 2.2.0 release 👀 Was about to install redbeat on our instance, might wait for a new (github linked) release.

**Comment by sibson** [comment]
2.2.0 is the latest release and available on pypi, https://pypi.org/project/celery-redbeat/.   The release "automation", https://github.com/sibson/redbeat/blob/main/makefile#L18-L35 doesn't include creating a GitHub Release, so it gets forgotten.  I'm not current with the latest best practices in the Python community, so if there is a better way to do things I'm all ears.

**Comment by iggy** [comment]
The original ask for this ticket was to get a release with the latest code from the main branch ( specifically https://github.com/sibson/redbeat/commit/ed3b3231668168dfd8f935f3035820e3b8e38f5d ). I should have made a separate ticket with the other observations in it.

fwiw, we are hitting the bug that ed3b323 fixes, so a new release with that commit would be useful
