### ISSUE TITLE
Celery 4.* Compatibility

### ISSUE THREAD

**Issue by eswald** [sibson/redbeat#49]
Currently, importing `redbeat.RedBeatScheduler` fails when using Celery 4.0.2, because `celery.utils.timeutils` has been renamed to `celery.utils.time`.  Then, the default schedule is ignored, because the configuration key has been renamed from `CELERYBEAT_SCHEDULE` to `beat_schedule`.  And that looks like just the tip of the iceberg.

Meanwhile, it may or may not be worth supporting multiple `celery` versions with a single codebase, but it's probably a good idea to document which versions are supported.

**Comment by sibson** [comment]
Your right I should document supported versions.  I believe celery 4.x should work if you try master, but please let me know if I've missing something.

**Comment by eswald** [comment]
Yes, master looks like it's working.  I apologize for not trying that first.

**Comment by sibson** [comment]
Docs now contain reference to celery 3 and 4, https://github.com/sibson/redbeat/pull/51/files#diff-88b99bb28683bd5b7e3a204826ead112R89.  I'm also planning to release 0.10 to pypi, which will support 3 and 4.   

Thanks for raising this issue, prior to those two changes the status wasn't very clear.
