### ISSUE TITLE
Lock timeout config value not correctly applied on Celery 4.x

### ISSUE THREAD

**Issue by jezdez** [sibson/redbeat#50]
When using redbeat on Celery 4.x it seems as if using `app.conf.CELERYBEAT_MAX_LOOP_INTERVAL` is wrong.

**Comment by jezdez** [comment]
PR coming up..

**Comment by jezdez** [comment]
@sibson I've opened #51 and would love to get feedback for it, I think it'll improve the compatibility between Celery 3 and 4 a lot and makes the config code path easier to understand. Cheers!

**Comment by blablacio** [comment]
I've made the same observations couple of days ago when our tasks started running twice. Would be great to see this merged and a new PyPi version released.

**Comment by blablacio** [comment]
@jezdez It seems I still need to explicitly set **REDBEAT_LOCK_TIMEOUT** in order to avoid duplication of tasks with your latest changes.

**Comment by jezdez** [comment]
@blablacio Hmm, can you check what the value of `app.conf.beat_max_loop_interval` for your Celery app is?

By default [it's 0](http://docs.celeryq.org/en/latest/userguide/configuration.html#beat-max-loop-interval). Redbeat at the moment uses that to calculate the default of the distributed lock timeout (`beat_max_loop_interval * 5`) and that hasn't changed in the PR from the previous behavior. Which is odd since the README makes it sound as if the feature is enabled by default:

> RedBeat uses a distributed lock to prevent multiple instances running. To disable this feature, set: REDBEAT_LOCK_KEY = None

So maybe this is an actual bug since it's not what users would expect.

**Comment by jezdez** [comment]
Aha, this gives a clue from the [Celery docs](http://docs.celeryq.org/en/latest/userguide/configuration.html#beat-max-loop-interval):

> The default for this value is scheduler specific. For the default Celery beat scheduler the value is 300 (5 minutes), but for the django-celery-beat database scheduler it’s 5 seconds because the schedule may be changed externally, and so it must take changes to the schedule into account.

In other words, I'm postulating that redbeat should not use the fallback config value of `beat_max_loop_interval` of 0, but instead define its own default.

Similar to [how django-celery-beat does](https://github.com/celery/django-celery-beat/blob/07911466542837b68483189d810f94b41e0c0f87/django_celery_beat/schedulers.py#L32-L35).

@sibson Does using _5_ seconds as the `beat_max_loop_interval` value and _25_ seconds for the distributed lock timeout sensible to you?

**Comment by blablacio** [comment]
@jezdez: I debugged earlier today and it is really strange that in scheduler.py I get `beat_max_loop_interval` of 0 while Celery itself advertises it as `maxinterval -> 5.00 minutes (300s)`. I guess the default value is 0 for third-party schedulers?

As for Celery docs -- I noticed this excerpt last week, which leads me to believe that somehow Celery assumes third party schedulers declare `beat_max_loop_interval` and ignores/resets defaults.

It's really weird as if I set **REDBEAT_LOCK_TIMEOUT** to a value < 300, duplicates appear again, so somehow default `beat_max_loop_interval` advertised by Celery comes into play...

I'll spend some more time on this tomorrow if you don't come up with a solution.

**Comment by blablacio** [comment]
@jezdez Okay, so it seems that the default scheduler uses **DEFAULT_MAX_INTERVAL** which is set to 300 in case nothing is passed on the command line and **CELERY_BEAT_MAX_LOOP_INTERVAL** setting is not defined. We're subclassing the default scheduler, so that's why we get a `max_interval` of 300 too.

I think that [scheduler.py line 81](https://github.com/jezdez/redbeat/blob/c73d114720eea47e552c95399999f20b1c2e784b/redbeat/schedulers.py#L81) should rather read:

> `return self.app.conf.get(self.max_loop_interval_config) or DEFAULT_MAX_INTERVAL`


instead. That way **DEFAULT_MAX_INTERVAL** will be picked up and used  if not overridden.

Not sure if it makes sense to define a default `beat_max_loop_interval` for the scheduler if we can override it on the command line or with **CELERY_BEAT_MAX_LOOP_INTERVAL** setting. Probably a matter of taste...

**Comment by blablacio** [comment]
@sibson Would you please chime in on the subject?

**Comment by jezdez** [comment]
@blablacio I think I've solved this a bit differently in 136cacc7e2cc4144e9e3bb1fcb821edc761db8e1. Could you try again on your side?

**Comment by jezdez** [comment]
Err I meant 64b1eaf4c18f1dfd7a2339e5d56562e9d587aab2.

**Comment by blablacio** [comment]
Okay, at first glance it seems to do the trick. Will test it later and get back to you. Thanks!

**Comment by jezdez** [comment]
@blablacio Thank you

**Comment by sibson** [comment]
thanks @jezdez and @blablacio for working on this, I'm just back from vacation.  It sounds like #51 is the way forward.  I'll wait for confirmation and look to merge the PR soonest.

**Comment by blablacio** [comment]
@jezdez Seems to be working fine here. One minor nitpick: when switching to Celery 4 I used the namespace feature: `app.config_from_object('django.conf:settings', namespace='CELERY')`, so **CELERYBEAT_SCHEDULE** became **CELERY_BEAT_SCHEDULE**. Then I switched to redbeat scheduler and I had to rename back to **CELERYBEAT_SCHEDULE**.

Would be great to take the namespace into consideration. Otherwise all looks good! Hopefully we'll see a new release to PyPi soon.

**Comment by jezdez** [comment]
@blablacio Huh, this should work as intended, the "CELERY" namespace is automatically filtered out by Celery itself, so when we [access the config variable](https://github.com/jezdez/redbeat/blob/5f2c723ab23a1d25f4b6edfb4fb225c157d043e6/redbeat/schedulers.py#L90-L95) it should read `CELERY_BEAT_SCHEDULE` automatically. Can you double check what `app.conf.beat_schedule` for your Celery app is?

Btw, I've also updated the docs in https://github.com/jezdez/redbeat/commit/5f2c723ab23a1d25f4b6edfb4fb225c157d043e6. See it [rendered here](https://github.com/jezdez/redbeat/tree/lock-settings#creating-tasks).

**Comment by blablacio** [comment]
@jezdez Please, disregard my previous comment. I think I just messed code up when I started debugging the issue last week...

All looks good after testing once again with and without defaults overridden for max_interval and lock_timeout.

@sibson I think you might want to test this out and push a release if you're happy with it.

Thanks guys!

**Comment by jezdez** [comment]
@blablacio Yaaay!! 🎆

**Comment by jezdez** [comment]
Closing the issue as #51 has been merged.

**Comment by sibson** [comment]
thanks @jezdez @blablacio for running with this issue. I've released 0.10.0 to pypi.
