### ISSUE TITLE
avoid using __type__ in jsonencoder

### ISSUE THREAD

**Issue by sibson** [sibson/redbeat#7]
Using a dunder method seems like a code smell. Is there a better way to do sniff the type and do the right thing?

**Comment by jlaine** [comment]
What specific line(s) of code does this refer to, I'm not sure it's still current?

**Comment by sibson** [comment]
I think this was refering to using `__type__` within the serialized JSON, I was hoping to find a more clever way to introspect.  I agree, it's moot at this point.
