### ISSUE TITLE
example is needed

### ISSUE THREAD

**Issue by qlygirl** [sibson/redbeat#73]
hi, i think this is a good project and want to use in my schedule job system. 
however i had met some problems when i'm using it. can you offer an small and complete example project? I know how to set config and set schedule info and so on, but still can't run them successfully. please? thank you

**Comment by dengjiuhong** [comment]
+1
hard to get start.

**Comment by sibson** [comment]
If you have a working [Celery Beat setup](http://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html), RedBeat should be enabled by following the [Getting Started](https://github.com/sibson/redbeat#getting-started) section.  I'd like to keep RedBeat docs focused on the differences between it and schedulers provided by Celery. If there is a way to include an small example that helps RedBeat users without digressing into too much Celery config, then I'd be happy to include it.

**Comment by zibuyu1995** [comment]
@qlygirl this is small and complete example :

### config.py
```python
#!/usr/bin/env python
# coding: utf-8

enable_utc = False
timezone = 'Asia/Shanghai'

broker_url = 'redis://:public@localhost:6379/15'

beat_scheduler = 'redbeat.RedBeatScheduler'

beat_max_loop_interval = 5

redbeat_redis_url = broker_url

redbeat_key_prefix = 'redbeat'
redbeat_schedule_key = redbeat_key_prefix + ':schedule'
redbeat_statics_key = redbeat_key_prefix + ':statics'
redbeat_lock_key = redbeat_key_prefix + ':lock'
redbeat_lock_timeout = beat_max_loop_interval * 5


beat_schedule = {
    'add-every-10-seconds': {
        'task': 'task.add_task',
        'schedule': 10.0,
        'args': (16, 16)
    },
    'add-every-5-seconds': {
        'task': 'task.test',
        'schedule': 5.0,
        'args': (16, 16)
    },
}
```

### task.py
```python
#!/usr/bin/env python
# coding: utf-8

import config

from celery import Celery
from datetime import datetime


app = Celery('test')
app.config_from_object(config)


@app.task
def add_task(a, b):
    print a + b
    return u'add task'


@app.task
def test():
    print datetime.now()
    return u'time test'
```

### run
```bash
celery -A task worker -l debug
celery  beat -S redbeat.RedBeatScheduler -A task -l debug
```

**Comment by qlygirl** [comment]
the example is helpful,  thanks!
