### ISSUE TITLE
Redis Connection Retry

### ISSUE THREAD

**Issue by geoolekom** [sibson/redbeat#77]
If Redis is temporary unavailbale, celery beat with RedbeatScheduler fails with Exceptions. 
It would be better to implement celery beat default behaviour. Beat should try to connect Redis with increasing interval.

**Comment by geoolekom** [comment]
Implemented in https://github.com/sibson/redbeat/pull/78

**Comment by jlaine** [comment]
I think this can be closed since #80 was merged
