### ISSUE TITLE
crontab type job getting picked up at beat startup

### ISSUE THREAD

**Issue by dmonojit** [sibson/redbeat#79]
Hi,

I am trying to use `redbeat` for crontab type periodic jobs.

The problem I am facing is that, the job runs once when I start celery beat in a separate tab, and then it also runs at the scheduled time.

The second run is as expected, but not the first one. Could anyone help me out in this?

My `celery.py` is as follows,
```
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_BROKER_URL = 'redis://{redis_host}:{redis_port}/{redis_db}'.format(
    redis_host=settings.REDIS_HOST, redis_port=settings.REDIS_PORT, redis_db=settings.REDIS_DB)
CELERY_RESULT_BACKEND = CELERY_BROKER_URL

app = Celery('tasks', broker=CELERY_BROKER_URL, backend=CELERY_RESULT_BACKEND, redbeat_redis_url=CELERY_BROKER_URL)

app.conf.update(
    accept_content=CELERY_ACCEPT_CONTENT,
    task_serializer=CELERY_TASK_SERIALIZER,
    result_serializer=CELERY_RESULT_SERIALIZER)

# Using a string here means the worker don't have to serialize
# the configuration object to child processes.
# - namespace='CELERY' means all celery-related configuration keys
#   should have a `CELERY_` prefix.
app.config_from_object('django.conf:settings')

# Load task modules from all registered Django app configs.
# This is not required, but as you can have more than one app
# with tasks it’s better to do the autoload than declaring all tasks
# in this same file.
app.autodiscover_tasks(lambda: settings.INSTALLED_APPS)

@app.on_after_configure.connect
def setup_periodic_tasks(sender, **kwargs):
    from api.tasks import sample_add_task
    sender.add_periodic_task(
        **crontab(hour=15, minute=50)**,
        sample_add_task.s(15, 30),
        name='add everyday'
    )
```

`sample_task.py`:
```
from __future__ import absolute_import
from celery import task

@task
def sample_add_task(number1, number2):
    print('This is a sample add task for numbers: {0} and {1}'.format(number1, number2))
    return(number1 + number2)
```

Celery worker command: `celery --app=app.celery worker --loglevel=INFO`
Celery worker logs:
```
[19/Jan/2018 15:51:25] DEBUG [django.db.backends:89] (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
[19/Jan/2018 15:51:25] DEBUG [django.db.backends:89] (0.000) SHOW FULL TABLES; args=None
[19/Jan/2018 15:51:25] DEBUG [django.db.backends:89] (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
[19/Jan/2018 15:51:25] DEBUG [django.db.backends:89] (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
[19/Jan/2018 15:51:25] DEBUG [django.db.backends:89] (0.001) SHOW FULL TABLES; args=None
[19/Jan/2018 15:51:25] DEBUG [django.db.backends:89] (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
[2018-01-19 15:51:27,571: INFO/MainProcess] Connected to redis://localhost:6379/4
[2018-01-19 15:51:27,577: INFO/MainProcess] mingle: searching for neighbors
[2018-01-19 15:51:28,589: INFO/MainProcess] mingle: all alone
[2018-01-19 15:51:28,595: INFO/MainProcess] celery@qplum-Precision-T1700 ready.
[2018-01-19 15:51:31,494: INFO/MainProcess] Events of group {task} enabled by remote.


[2018-01-19 15:51:46,508: INFO/MainProcess] Received task: api.tasks.sample_task.sample_add_task[15684a45-5f45-4070-a229-4331555e4863]  
[2018-01-19 15:51:46,510: WARNING/ForkPoolWorker-7] This is a sample add task for numbers: 15 and 30
[2018-01-19 15:51:46,512: INFO/ForkPoolWorker-7] Task api.tasks.sample_task.sample_add_task[15684a45-5f45-4070-a229-4331555e4863] succeeded in 0.0018646069802343845s: 45


[2018-01-19 15:55:00,117: INFO/MainProcess] Received task: api.tasks.sample_task.sample_add_task[299ce531-a877-4925-886f-bb512c7caa2c]  
[2018-01-19 15:55:00,121: WARNING/ForkPoolWorker-1] This is a sample add task for numbers: 15 and 30
[2018-01-19 15:55:00,123: INFO/ForkPoolWorker-1] Task api.tasks.sample_task.sample_add_task[299ce531-a877-4925-886f-bb512c7caa2c] succeeded in 0.002788302954286337s: 45
```

Celery beat command: `celery beat -S redbeat.RedBeatScheduler --app=app.celery`
Celery beat logs:
```
celery beat v4.1.0 (latentcall) is starting.
[19/Jan/2018 15:51:45] DEBUG [django.db.backends:89] (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
[19/Jan/2018 15:51:45] DEBUG [django.db.backends:89] (0.030) SHOW FULL TABLES; args=None
[19/Jan/2018 15:51:45] DEBUG [django.db.backends:89] (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
[19/Jan/2018 15:51:45] DEBUG [django.db.backends:89] (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
[19/Jan/2018 15:51:45] DEBUG [django.db.backends:89] (0.000) SHOW FULL TABLES; args=None
[19/Jan/2018 15:51:45] DEBUG [django.db.backends:89] (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
__    -    ... __   -        _
LocalTime -> 2018-01-19 15:51:46
Configuration ->
    . broker -> redis://localhost:6379/4
    . loader -> celery.loaders.app.AppLoader
    . scheduler -> redbeat.schedulers.RedBeatScheduler
       . redis -> redis://localhost:6379/4
       . lock -> `redbeat::lock` 25.00 minutes (1500s)
    . logfile -> [stderr]@%WARNING
    . maxinterval -> 5.00 minutes (300s)
```

Redis data of the job:

After first run -
```
127.0.0.1:6379[4]> HGETALL "redbeat:add everyday"
1) "meta"
2) "{\"last_run_at\": {\"day\": 19, \"hour\": 15, \"__type__\": \"datetime\", \"year\": 2018, \"month\": 1, \"second\": 46, \"microsecond\": 497316, \"minute\": 51}, \"total_run_count\": 1}"
3) "definition"
4) "{\"enabled\": true, \"args\": [15, 30], \"schedule\": {\"month_of_year\": \"*\", \"hour\": 15, \"__type__\": \"crontab\", \"day_of_week\": \"*\", \"day_of_month\": \"*\", \"minute\": 55}, \"name\": \"add everyday\", \"kwargs\": {}, \"task\": \"api.tasks.sample_task.sample_add_task\", \"options\": {}}"
```

After second (scheduled) run -
```
127.0.0.1:6379[4]> HGETALL "redbeat:add everyday"
1) "meta"
2) "{\"last_run_at\": {\"day\": 19, \"hour\": 15, \"__type__\": \"datetime\", \"year\": 2018, \"month\": 1, \"second\": 0, \"microsecond\": 112246, \"minute\": 55}, \"total_run_count\": 2}"
3) "definition"
4) "{\"enabled\": true, \"args\": [15, 30], \"schedule\": {\"month_of_year\": \"*\", \"hour\": 15, \"__type__\": \"crontab\", \"day_of_week\": \"*\", \"day_of_month\": \"*\", \"minute\": 55}, \"name\": \"add everyday\", \"kwargs\": {}, \"task\": \"api.tasks.sample_task.sample_add_task\", \"options\": {}}"
```

Clearly, the first run is not at all at the scheduled time and got triggered just after beat startup!

Please note, this issue does not happen when I use standard `PersistentScheduler` with celery beat.

**Comment by sibson** [comment]
I've not used crontab jobs personally.  There is likely a difference between how is_due() gets evaluated that doesn't play well with RedBeat.

**Comment by WesDowney** [comment]
I confirmed the same behavior where when crontab is being used, it runs the task once at startup and then again at the time it should run.

**Comment by tredzko** [comment]
It doesn't appear as though beat is expecting `crontab` to trigger the task, so it's firing if the specified interval is within the beat as well as on the interval itself. It makes sense then that `is_due` will return `True`, since the last run will always be before the provided `crontab` interval.

**Comment by sibson** [comment]
FWIW, my hunch is,  the handling of ```last_run_at``` for a task that has never executed is causing the issue. Something about how [crontab](https://github.com/sibson/redbeat/blob/master/redbeat/decoder.py#L47) and [Entry](https://github.com/sibson/redbeat/blob/master/redbeat/schedulers.py#L174-L175) get created, in that they are not handling None how RedBeat expects.  That then causes [due_at](https://github.com/sibson/redbeat/blob/master/redbeat/schedulers.py#L181-L183) to misfire or maybe its the logic in due_at that needs to be smarter.

**Comment by jgerry2002** [comment]
Any news on the testing? Were you able to alter last_run_at and prevent duplicates?

**Comment by joekohlsdorf** [comment]
This isn't a surprise at all, it's in the code: https://github.com/sibson/redbeat/blob/97223a6fec5c71bec8086d4c694443b713a4e643/redbeat/schedulers.py#L225

**Comment by tredzko** [comment]
@joekohlsdorf It's a bit of a surprise, since it's not that apparent what the meta default is and it goes against what the default is for Celery beat. I'm not intimately familiar with Celery Beat or RedBeat, so could you show me where the meta value for this is set and how we might be able to circumvent/set it?

**Comment by joekohlsdorf** [comment]
https://github.com/sibson/redbeat/blob/97223a6fec5c71bec8086d4c694443b713a4e643/redbeat/schedulers.py#L203-L205

**Comment by tredzko** [comment]
The comment mentions that it's confusing and wrong, though the reason might not be obvious. I'm going to agree with your assessment that this override is to make sure that the jobs get run in case Redbeat goes down. Based off of this, I'm not sure much can be done aside from pre-populating the meta in Redis in some way (without code changes obviously 😄 ). Thanks for your insight @joekohlsdorf !

**Comment by sibson** [comment]
I'd love to make redbeat handle crontab better and in a more predicable way, preferably in line with how native celery does.  I simply don't have enough context in my head to figure out why it isn't working or how to fix it.  If someone is able to create a PR that does the right thing in both periodic and crontab cases I'd be happy to accept it.

**Comment by tredzko** [comment]
@sibson What's the expected behavior? We can try to take a look to see if we can get to line up and get PR made.

**Comment by joekohlsdorf** [comment]
Can you confirm that the same really doesn't happen for periodic tasks?
To me it looks like the code will always immediately fire new tasks, no matter if cronjob or periodic, celerybeat doesn't work like this. The way redbeat is implemented it would execute missed tasks even if we change the default to the current time.

**Comment by sibson** [comment]
I think the two principles are a) do what celery does b) do what makes sense. I don't know which principle wins if the two are in conflict.  It could be I made a bad choice and we need to either stick with it for consistency or fix it and move towards a 2.x branch.

I suspect the [relative kwarg](http://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html#id4) might also be complicating matters for PeriodicTasks and is something RedBeat should support better.  

The first step is likely defining and agreeing what should happen in the various cases and what actually happens.  Then we can better evaluate if there is a small fix or a larger change to be made.

**Comment by cpattersonit** [comment]
> Based off of this, I'm not sure much can be done aside from pre-populating the meta in Redis in some way (without code changes obviously 😄 ).

@tredzko I discovered the easiest way (at least in my use case) to accomplish this is to call the `reschedule()` method on a RedBeatSchedulerEntry instance immediately after saving one.
