### ISSUE TITLE
Duplicate tasks

### ISSUE THREAD

**Issue by virusdefender** [sibson/redbeat#81]
https://github.com/virusdefender/redbeat_test

```
app.conf.beat_schedule = {
    'task': {
        'task': 'app.tasks.task_run',
        'schedule': crontab(hour=8, minute=0)
    },
}
```

Set your computer's clock to 07:59:00 (UTC timezone)

Then start the worker and redbeat process

```
celery -A redbeat_test worker -l debug

celery beat -S redbeat.RedBeatScheduler -A redbeat_test -l debug
```

![image](https://user-images.githubusercontent.com/4939404/35668039-d0993316-076a-11e8-99c2-7f557c7b81a0.png)

You will see a task is submitted when redbeat is started at `2018-02-01 07:59:41,550`

PS: 

 - Maybe you need to flush redis between tests
 - It seems that a fresh task with `last_run_at == None` enters `maybe_xxx` logic will cause problem

**Comment by richardasaurus** [comment]
I'm also seeing my crontab task ran duplicate times. If I add more workers it runs the task I want to run them all, many time. This is very bad. 

```
[2018-03-24 05:01:00,096: INFO/ForkPoolWorker-3] Daily forecast started
[2018-03-24 17:10:03,067: INFO/ForkPoolWorker-1] Daily forecast started
[2018-03-24 17:10:04,050: INFO/ForkPoolWorker-2] Daily forecast started
[2018-03-25 05:00:55,104: INFO/ForkPoolWorker-6] Daily forecast started
[2018-03-25 05:01:00,066: INFO/ForkPoolWorker-5] Daily forecast started
[2018-03-25 12:46:20,378: INFO/ForkPoolWorker-1] Daily forecast started 
```

This should be happening on a single worker only. Please advise how we can avoid this @sibson

**Comment by richardasaurus** [comment]
Is this lib being maintained still?

**Comment by sibson** [comment]
I've not used crontab jobs personally.  There is likely a difference between how is_due() gets evaluated that doesn't play well with RedBeat.

**Comment by az-wegift** [comment]
I think this is related to celery/celery#4493 and might be the same issue as #79.

The behaviour is pretty straightforward to reproduce. Run scheduler, let it spawn a task. Just before spawning another one, stop the scheduler and start it after at least one task period. Celery will try to make up for the missed run. This is not a bug, but intended behaviour. Although I'd argue whether it is intuitive, because this is not how cron behaves by default.

**Comment by az-wegift** [comment]
If am correct, then the fix should be in Celery itself - as an option to either make up for missed run or not.

**Comment by davidjmemmett** [comment]
Given that the fix for this issue was reverted recently, should this issue be re-opened? I'm looking into similar behaviour which is causing tasks to be repeated on subsequent minutes.

**Comment by sibson** [comment]
I didn't revert the change, I created a PR to see if it was related to test failures on master.
