### ISSUE TITLE
How to ensure only one entry for scheduled job is added on subsequent restarts?

### ISSUE THREAD

**Issue by rajeshyogeshwar** [sibson/redbeat#86]
I want to add an entry for a job into Redis when celery is started. In order to do so I need to ensure that the entry is not duplicated in subsequent restarts. Is there a way provided to do so? If not, is there a possibility for me checking by task name?

**Comment by sibson** [comment]
I think https://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html#crontab-schedules does what you want.  If not could you provide more details.

**Comment by rajeshyogeshwar** [comment]
@sibson owing to the fact that the question is a almost 18 months old, I definitely found an alternate way. But thanks for responding.
