### ISSUE TITLE
AttributeError: 'PersistentScheduler' object has no attribute 'lock_key'

### ISSUE THREAD

**Issue by kvbulusu** [sibson/redbeat#87]
Hi,
A newbie here...I'm seeing the following error when trying to insert task direction into redis using zadd. Here is what  I have

app = Flask(__name__)
app.config['broker_url'] = 'redis://localhost:6379/0'
app.config['result_backend'] = 'redis://localhost:6379/0'
app.config['redbeat_redis_url'] = "redis://localhost:6379/1"
app.config['CELERY_BEAT_SCHEDULER '] = 'RedBeatScheduler'
app.config['beat_max_loop_interval'] = 50
app.config['result_expires'] = 60
celery = Celery(app.name, broker=app.config['broker_url'])
celery.conf.update(app.config)
redis_url =  'redis://localhost:6379/0'
r = redis.Redis.from_url( redis_url )
score = utc_time.timestamp + 450
r.zadd('RedBeatScheduler', 'copdAlerts',score)

%celery worker -A  test_v1.celery --loglevel=debug -E -B -S RedBeatScheduler

[2018-03-26 22:24:26,039: ERROR/Beat] Signal handler <function acquire_distributed_beat_lock at 0x7f80b0dd3c08> raised: AttributeError("'PersistentScheduler' object has no attribute 'lock_key'",)
Traceback (most recent call last):
  File "/home/kvb/.virtualenvs/Notifications/local/lib/python2.7/site-packages/celery/utils/dispatch/signal.py", line 233, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/kvb/.virtualenvs/Notifications/local/lib/python2.7/site-packages/redbeat/schedulers.py", line 422, in acquire_distributed_beat_lock
AttributeError: 'PersistentScheduler' object has no attribute 'lock_key'

Not sure what else to debug or where to look...I checked the object doesnt have lock_key ....Any suggestions?

**Comment by sibson** [comment]
I'm not familiar with Celery setup for Flask, but you shouldn't see PersistentScheduler, it should be RedBeatScheduler.  That leads me to believe there is a configuration issue.

**Comment by kvbulusu** [comment]
It was config issue. Thanks for the comment.

**Comment by mrcljx** [comment]
You're likely not passing `--scheduler=redbeat.RedBeatScheduler` to `celery beat`.
