### ISSUE TITLE
Support for Redis SSL connections

### ISSUE THREAD

**Issue by gunthercox** [sibson/redbeat#99]
Does redbeat support SSL connections to redis?

In many cases such as Microsoft Azure's redis caches, SSL connections are required by default.
~ https://docs.microsoft.com/en-us/azure/redis-cache/cache-configure#access-ports

I noticed that Celery now has settings that allow SSL to be enabled but I can't seem to find anything in this repository that suggests that redbeat might support this type of connection.
~ http://docs.celeryproject.org/en/latest/userguide/configuration.html#redis-backend-use-ssl

**Comment by sibson** [comment]
I just works ™️ if you are using ```rediss://``` URIs.  I don't think we have a way to support certs and it also might make sense to have an option to enforce SSL and avoid silent reversion to an unsafe transport.

**Comment by gunthercox** [comment]
Okay, thank you very much.
